### PR TITLE
Added support for caffeinate

### PR DESCRIPTION
**Pull request by aryamannaik**
# Advanced HW 9 submission

Closes None

Name: [Aryaman Naik]
Uniqname: [aryaman]

### CODE REVIEW

**Comment by mterwill** [comment]
Hunh! I've used Caffeine for years and years with no idea this was behind the curtain.

**Comment by aryamannaik** [comment]
Yeah, I haven't tried it, but I assume you could use it within a program if you needed such functionality.

**Comment by mterwill** [comment]
This looks good to me. PR is sufficient, I'll mark you down as having completed adv hw 7. Thanks!

**Comment by aryamannaik** [comment]
Thanks!

**Pull request merged**
