### PR TITLE
added the date.md file

### LINKED ISSUE #159: date

### PR DESCRIPTION
**Pull request by aritrach**
# Advanced HW 9 submission

Closes #159 

Name: Aritra Chakrabarty
Uniqname: aritrac

### CODE REVIEW

**Comment by mterwill** [comment]
@aritrach I know we talked in my OH and I mentioned you'll want to add more to `date`. I'd make sure to do this for credit, as it's not complete enough as-is!

**Comment by themoh** [comment]
We'll be closing all pull requests at midnight tonight, so please have this done by then.

**Comment by the-alex** [comment]
This `.md` file does not render properly. Test on your local system and make modifications accordingly.
screen shot 2016-03-27 at 11 26 21 pm

**Comment by aritrach** [comment]
Hi, it's rendering correctly on my local directory. Any advice on what I should do?
screenshot from 2016-03-27 23-35-55

**Comment by themoh** [comment]
It's rendering fine on my machine as well. Add in bullet points (see other merged requests) and you should be good to go.

**Comment by aritrach** [comment]
Hi again! I tried changing the formatting by getting rid of all the # signs. I have added a picture of it working on my machine again. As you will see, the font size is now different.
screenshot from 2016-03-27 23-47-58

**Pull request merged**
