### PR TITLE
Added the entry for jobs

### LINKED ISSUE #31: Jobs
I will be doing the 'jobs' command

### PR DESCRIPTION
**Pull request by rgysin**
Preview available below

Closes #31

### CODE REVIEW

**Comment by mterwill** [comment]
Columns don't line up several places for me
screen shot 2016-03-21 at 5 17 04 pm

Also please add a section _What is a job?_

**Comment by arxanas** [comment]
It should probably mention <kbd>C-z</kbd> to background the current process. @mterwill Is it worth mentioning `fg` to explain how to bring a job to the foreground?

**Comment by ppannuto** [comment]
Yes, `fg` is useful. Especially showing how to pick a job out of the jobs list
to foreground (also useful to show kill %N, where N is a job if that's not
already there).

> On Mar 22 2016, at 3:57 pm, Waleed Khan &lt;notifications@github.com&gt;
wrote:  

>

> It should probably mention C-z to background the current process.
[@mterwill](https://github.com/mterwill) Is it worth mentioning fg to explain
how to bring a job to the foreground?

>

> —  
You are receiving this because you are subscribed to this thread.  
Reply to this email directly or [view it on GitHub](https://github.com/c4cs/c4
cs.github.io/pull/56#issuecomment-199990934)

**Comment by mterwill** [comment]
Looks like someone else wrote on `fg`? #150 

Also <kbd>hello</kbd><kbd>so</kbd><kbd>cool</kbd>

**Comment by ppannuto** [comment]
@mterwill @arxanas We should consider doing a cleanup pass at some point, possibly consolidating somethings that are only useful together onto one page (i.e. jobs/fg/bg).

@rgysin This looks pretty good to me. I'm going to merge this. Thanks!

**Pull request merged**
