### PR TITLE
Clear

### LINKED ISSUE #60: clear

### PR DESCRIPTION
**Pull request by cnees**
Updates branch that resolves #60 
Name: Clara Nees
Uniquename: cnees

### CODE REVIEW

**Comment by the-alex** [comment]
I would add one bullet point motivating the use of the command, basically to answer the question "Why would I ever use this command?"  For instance, I use this command whenever I want to run a program and have only the output of that program be in my terminal, so I don't get it confused with output above or below the command.

**Comment by ppannuto** [comment]
It might be good to also add a pointer here to the "reset" command. If you
ever accidentally cat a binary file or something and your terminal gets
messed up (can't type, funny characters, etc), reset will fix it.

[I'm not sure if reset is on the list yet, but it should be. If it's
missing, please add it to the command list under shells as well]

**Comment by mterwill** [comment]
Closes #76

**Comment by the-alex** [comment]
@cnees

**Comment by cnees** [comment]
Reset is on the list already, but no one has claimed it.
I've added a use case bullet point for the clear command.

**Pull request merged**
