### PR TITLE
Updated the cp command

### LINKED ISSUE #66: cp

### PR DESCRIPTION
**Pull request by GautamRajagopal**
# Advanced HW 9 submission

Closes #66 

Name: Gautam Rajagopal
Uniqname: rgautam

### CODE REVIEW

**Comment by mterwill** [comment]
Don't forget to add a `<!--more-->` tag somewhere so it previews correctly on the site. See other merged files for an example.

**Comment by mterwill** [comment]
Looks pretty good overall. One more suggestion for an example:

`cp *.pdf ~/Desktop` to illustrate how you could take all PDFs out of your current directory (say some complicated path like `~/Dropbox/classes/eecs398/ahw/9/` and drop them on the Desktop (with the same names) so you can quickly upload to Gradescope.

**Comment by GautamRajagopal** [comment]
I made a few changes. I don't have to issue a new pull request, do I?

**Comment by mterwill** [comment]
Nope. Looks good!

**Pull request merged**
