### PR TITLE
Advanced Homework 7 submission

### LINKED ISSUE #259: create a reference page for 'toys/cmatrix'

### PR DESCRIPTION
**Pull request by yanqwang**
# Advanced HW 7 submission

Closes #259

Name: Yanqi Wang
Uniqname: yanqwang

### CODE REVIEW

**Comment by mterwill** [comment]
Could you explore a couple of the flags in `man cmatrix` and add those in?

**Comment by yanqwang** [comment]
I've already did! Do I need to pull a new request again?

**Comment by mterwill** [comment]
Cool! No need to make another PR, but the formatting looks a little off to me – make sure if you want something to appear as a `code snippet` you \`enclose that text in backticks\`.

Example:

image

**Comment by mterwill** [comment]
@yanqwang could you please fix these formatting issues?

**Comment by yanqwang** [comment]
I updated it! Is this version okay now?

**Comment by mterwill** [comment]
Looks good; thanks for fixing those flags up. Merging + giving you credit.

**Pull request merged**
