### PR TITLE
Added whereis.md documentation

### LINKED ISSUE #21: whereis

### PR DESCRIPTION
**Pull request by mzwee**
# Advanced HW 9 submission

Closes #21

Name: Miao Zi Wee
Uniqname: mzwee

### CODE REVIEW

**Comment by ppannuto** [comment]
The goal is not to recreate man pages:

screen shot 2016-03-24 at 16 46 11

Don't include all of the flags, choose the two or three that are most likely to be useful to people. Add real examples that use those flags that show what they do an why they're useful (i.e. what problem could you have that you need to use whereis to solve?)

**Comment by mzwee** [comment]
I've pushed a commit with updated whereis.md.

**Comment by mterwill** [comment]
Would be nice to see a sentence comparing/contrasting with `which`.

**Comment by mzwee** [comment]
I've pushed a commit with comparisons between `which` and `whereis`.

**Comment by mterwill** [comment]
Looks good to me.

**Pull request merged**
