### PR TITLE
ping.md HW5

### LINKED ISSUE #467: Writing Documentation for the "ping" command

### PR DESCRIPTION
**Pull request by anacuza**
# Advanced HW 5 submission

Closes #467

Name: Anamaria Cuza
Uniqname: anacuza

### CODE REVIEW

**Comment by AmritHariharan** [comment]
The Travis build is failing its checks, you seem to have a lot of files under the `/_site` directory that should be ignored by the gitignore. Did you try force builds/commits?

**Comment by anacuza** [comment]
I did get some errors at some point, that I tried working my way around them... Do we have access to the slides from the OH++, to check if I did the right steps? Thanks!

**Comment by samiurkh1n** [comment]
Slides are here: https://c4cs.github.io/lectures/w18/ohplusplus1#1

**Comment by anacuza** [comment]
Thanks, I went through all the steps and it still did not work: 
- I set up bundle exec Jekyll
- I created a new branch
- I created a new commit
- ran : git push --set-upstream <branch_name> master (since the command in the slide didn't work)

This is what I got:
fatal: Invalid gitfile format: ping.md
fatal: Could not read from remote repository.

**Comment by cyanliu** [comment]
Where did you put ping.md? It should be in a subfolder somewhere in the `_commands` folder, but I don't see the file anywhere in your repository.

**Comment by cyanliu** [comment]
Closing this PR because it seems to have been replaced by #589

**Pull request closed without merging**
