### PR TITLE
poweroff

### LINKED ISSUE #143: poweroff
I am claiming poweroff.

### PR DESCRIPTION
**Pull request by jbochu**
# Advanced HW 9 submission

Closes #143 

Name: JOSHUA BOCHU
Uniqname: jbochu

### CODE REVIEW

**Comment by mterwill** [comment]
You'll need to add a `<!--more-->` tag to get this to show up on the website.

**Comment by mterwill** [comment]
Mention `reboot`?

**Comment by themoh** [comment]
We'll be closing all pull requests at midnight tonight, so please have this done by then.

**Comment by jbochu** [comment]
You got it


Sent from Outlook






On Sun, Mar 27, 2016 at 12:45 PM -0700, "Mo" <notifications@github.com> wrote:












We'll be closing all pull requests at midnight tonight, so please have this done by then.

**Comment by mterwill** [comment]
Sorry, Joshua, you've still got some formatting errors in here and I still don't feel that your documentation is complete enough for credit. Part of the assignment was allowing ample time to complete the review process. You'd have needed to do the following before the deadline (last night):

1. add a `<!--more-->` tag as I requested
2. talk about the scheduling of `shutdown` or other useful command line options
3. remove the extra `~~~` on line 19

We won't be able to accept this.

**Pull request closed without merging**
