### PR TITLE
added logsave.md

### LINKED ISSUE #178: logsave

### PR DESCRIPTION
**Pull request by shinreey**
# Advanced HW 9 submission

Closes #178 

Name: Xinrui Yang
Uniqname: xryang

### CODE REVIEW

**Comment by ppannuto** [comment]
It looks like you put this in the root _commands directory. We would like to categorize things.

As this is a linux-only command, let's put it in the "Ubuntu" section [I'll rename that to Linux / Ubuntu later].

**Comment by ppannuto** [comment]
Can you also expand your example to show what the output of logsave looks like?

**Comment by ppannuto** [comment]
Also, adding some text that explains what applications its useful for (scripting, system services, backgrounded tasks, etc). Especially if you can give a specific example where you've used logsave / found it useful.

**Comment by ppannuto** [comment]
If you could also add an example that shows off some of its options -- it doesn't have very many ones, but showing how the `-a` flag affects its behavior with sample runs with and without it would be great.

**Comment by shinreey** [comment]
Do I have to do another pull request to add another example?

**Comment by ppannuto** [comment]
If you push more commits to the branch you made the PR from, the PR will
automatically update.

> On Mar 24 2016, at 11:14 pm, Xinrui &lt;notifications@github.com&gt; wrote:  

>

> Do I have to do another pull request to add another example?

>

> —  
You are receiving this because you commented.  
Reply to this email directly or [view it on GitHub](https://github.com/c4cs/c4
cs.github.io/pull/181#issuecomment-201120088)

**Comment by shinreey** [comment]
Ok! I just pushed... did that work?

**Comment by shinreey** [comment]
YES i see the commit! woo!

**Comment by shinreey** [comment]
Also - how do I put it in the Linux/Ubuntu directory?

**Comment by the-alex** [comment]
It looks like you made some changes! However, we need to have this command moved into the `_commands/ubuntu/` folder. I know that folder doesn't exist yet, but trust me, if you make it and put your `logsave.md` file in there and look at how the thing renders, it'll show up on the website.

**Comment by shinreey** [comment]
Ok, I'll do that right now

**Pull request merged**
