### PR TITLE
CSV stands for comma-separated VALUES

### PR DESCRIPTION
**Pull request by cnees**
not comma-separated vector. RFC: https://tools.ietf.org/html/rfc4180

### CODE REVIEW

**Comment by the-alex** [comment]
Nice catch! We talked about that in our meeting and forgot to change it.

**Comment by mterwill** [comment]
Can you port this to c4cs/assignments like #211 per @the-alex's comment?

**Comment by the-alex** [comment]
@mterwill I think I already changed this particular issue myself.

**Comment by mterwill** [comment]
Thanks!






On Mon, Mar 28, 2016 at 5:44 PM -0700, "Alex Chojnacki" <notifications@github.com> wrote:












@mterwill I think I already changed this particular issue myself.

**Pull request merged**
