### PR TITLE
curl.md

### LINKED ISSUE #138: curl
Writing documentation for curl

### PR DESCRIPTION
**Pull request by serranic**
# curl.md

Closes #138

Name: Nicholas Serra
Uniqname: serranic

### CODE REVIEW

**Comment by mterwill** [comment]
You'll need to move this file to the correct location – please check out other, closed pull requests for an example.

**Comment by serranic** [comment]
This should be good now.

**Comment by mterwill** [comment]
It's still showing as `_commands/tools/ADHW9.mdown`. We're looking for `_commands/tools/curl.md`.

You can see what files changed in your PR at https://github.com/c4cs/c4cs.github.io/pull/139/files.

As for Travis failing, I'll take care of that.

**Comment by mterwill** [comment]
Nice. Looks good!

**Pull request merged**
