### PR TITLE
Added documentation for locate command

### LINKED ISSUE #324: Add new documentation for "locate" command

### PR DESCRIPTION
**Pull request by shutas**
# Advanced HW 5 submission

Closes #324

Name: Shuta Suzuki
Uniqname: shutas

### CODE REVIEW

**Comment by shutas** [comment]
I am a little confused with why the check failed... what did I do wrong?

**Comment by mterwill** [comment]
You didn't do anything wrong. Travis fails periodically as documents are released before they're uploaded, resulting in dead links. Fixed the issue + re-ran your build.

**Comment by mterwill** [comment]
@shutas: please follow up by this Friday or we'll close the PR and won't be able to give you credit for the assignment.

**Comment by shutas** [comment]
I updated the file regarding your previous post. Does it look all set?

**Comment by mterwill** [comment]
Looks good to me. Thanks for fixing that up!

**Pull request merged**
