### PR TITLE
set command for advanced homework 9

### LINKED ISSUE #141: set
Claiming set!

### PR DESCRIPTION
**Pull request by rositawong**
# Advanced HW 9 submission

Closes #141 

Name: Rosita Wong
Uniqname: rositawo

### CODE REVIEW

**Comment by mterwill** [comment]
I'd like for you to mention a couple of other useful things you can do with `set`!

**Comment by themoh** [comment]
We'll be closing all pull requests at midnight tonight, so please have this done by then.

**Comment by the-alex** [comment]
I'm very sorry, but I must close this PR as it is past the deadline for submissions.

**Comment by rositawong** [comment]
Sorry I didn't see these comments. Does this mean I did not receive credit for this submission?

**Comment by mterwill** [comment]
Correct, unfortunately we are unable to offer credit for PRs that did not complete the revision process.

**Pull request closed without merging**
