### PR TITLE
Add reference page for `fortune`

### LINKED ISSUE #65: fortune

### PR DESCRIPTION
**Pull request by nkorth**
Fixes #65
uniqname: nkorth

### CODE REVIEW

**Comment by nkorth** [comment]
The build fails because I linked to cowsay.html, which doesn't exist yet. (#25)

Pretty cool that it can automatically check for broken internal links, I didn't expect that!

**Comment by the-alex** [comment]
Well, since it isn't there, we probably shouldn't include it.
If you can remove the link and leave your full name and unqiename so I can merge and give you credit, that'd be awesome.

**Comment by ppannuto** [comment]
Actually, I think it'd be better to copy over the template and move cowsay
to the incomplete list. Would rather have the link eventually.

**Comment by the-alex** [comment]
Alright, I took care of it. PR is good to go. Thanks again, Nathan!

**Pull request merged**
