### PR TITLE
Added hash reference

### LINKED ISSUE #305: Create reference for hash
Creating a reference for hash command that displays a hash table of recently executed programs.

### PR DESCRIPTION
**Pull request by sgurnoor**
# Advanced HW 5 submission

Closes #305

Name: Gurnoor Singh
Uniqname: gurnoor

### CODE REVIEW

**Comment by mterwill** [comment]
Cool! Didn't know about this one. What happens if `PATH` changes? [How] does the hash table get invalidated?

**Comment by mterwill** [comment]
@sgurnoor: please follow up by this Friday or we'll close the PR and won't be able to give you credit for the assignment.

**Comment by sgurnoor** [comment]
Fixed!

**Comment by mterwill** [comment]
Thanks! You're all set.

**Pull request merged**
