### PR TITLE
added atom to the editors

### PR DESCRIPTION
**Pull request by tianhaoz95**
# Advanced HW 7 submission

Closes # not in there, a new feature

Name: Tianhao Zhou
Uniqname: tianhaoz

added a link to the download page and a link to more packages.

### CODE REVIEW

**Comment by mterwill** [comment]
I appreciate the 'cool packages' section. I would love to see links to the relevant packages, in addition to a download link for the text editor.

Feels like you're underselling a bit – is there anything else you could add?

**Comment by tianhaoz95** [comment]
I just added a link to the download page and a link to all the packages.

**Comment by mterwill** [comment]
@tianhaoz95: thanks for adding the links. I would still like to see a little more on Atom before merging.

**Comment by ppannuto** [comment]
Hey @tianhaoz95, this is an okay start, but we're looking for some content that would make this accessible to new users. For example, in "why atom", explain why someone would care that it's "cross-platform". Under the "cool pacakages", a little more explanation of what the packages do or why people would want to use those packages. How would I search for packages if wanted to find a new one?

Atom's a little trickier, because it's not a smaller, contained tool like the other things in the reference section, but hopefully the suggestions I gave above should help fill the content gap Matt's pointed out.

Let's try to get this finished by Friday?

**Comment by tianhaoz95** [comment]
Hi professor Pannuto
I have just updated it. I think it should look more detailed this time.

Thanks,
Tian

**Comment by mterwill** [comment]
Looking much better! Thanks. Will merge + give you credit.

**Pull request merged**
