### PR TITLE
Added touch reference page

### PR DESCRIPTION
**Pull request by jrectorb**

### CODE REVIEW

**Comment by jrectorb** [comment]
Just realized we were supposed to add an issue before doing this and saw touch was already claimed.  Oops on this request.  Disregard it please.

**Comment by mterwill** [comment]
Well hold on. You already did all of this work... @mbremerkamp have you already started documenting ``touch``? If not, please consider letting @jrectorb take it! Comment here to confirm.

**Comment by mbremerkamp** [comment]
It's fine if you take the touch command.

**Comment by mterwill** [comment]
Nice job! Very complete. My only request is you use Markdown inline code (surround in backticks ` ) where appropriate (options, command excerpts, etc.) `like so`

Also, take a look at your header sizes (Break it down is two different sizes)

**Comment by jrectorb** [comment]
Updated the formatting.  Let me know if that's better!

**Comment by mterwill** [comment]
Looks great!

**Pull request merged**
