### PR TITLE
Add rsync reference page

### LINKED ISSUE #41: rsync

### PR DESCRIPTION
**Pull request by dmacewen**
Added rsync reference page. Closes #41

### CODE REVIEW

**Comment by mterwill** [comment]
This feels like it's underselling rsync somehow? It's such a cool and powerful tool, but part of it's beauty is definitely the simplicity. I'll give you a :+1: and wait for another staff member to merge.

**Comment by ppannuto** [comment]
Sorry for the slow response from me on this one. These examples aren't really complete. If you type `rsync -r` into a terminal, it won't do anything. The idea of the examples section is to show full examples of what happens when you run a command, i.e. in the case of rsync, the directory structure before and after running rsync.

The idea of showing different options is to show off how rsync behaves differently when they're used. The idea is that someone who's never used rsync should be able to skim over this and see some examples of what it does and hopefully be able to work from those.

There's not enough here yet.

**Comment by dmacewen** [comment]
Hi Professor Pannuto,

I added a lot of changes to rsync including more examples, better
explanations of commands, and a comparison to scp. The changes are pushed
to the same branch that I submitted previously for a pull request. Sorry
for the misunderstanding.

Thanks,
Doug

**Comment by mterwill** [comment]
Much more complete! Will assign to Pat for the final say.

**Comment by ppannuto** [comment]
Much better! Nice work, thanks :)

**Pull request merged**
