### PR TITLE
Create a reference page for 'bg'

### LINKED ISSUE #250: create a reference page for 'bg'

### PR DESCRIPTION
**Pull request by cesmi**
# Advanced HW 7 submission

Closes #250

Name: Christian Smith
Uniqname: cesm

### CODE REVIEW

**Comment by mterwill** [comment]
This looks good overall. I'd really appreciate it if you could link to the appropriate pages for `fg` and `jobs`, then go through those pages as well and add links to one another.

**Comment by mterwill** [comment]
Thanks! Merging + giving you credit.

**Comment by cesmi** [comment]
Thanks Matt! Just to clarify, no need for me to come to office hours then?

**Comment by mterwill** [comment]
Nope! You're all set.

**Pull request merged**
