### PR TITLE
Added documentation for open (osx)

### PR DESCRIPTION
**Pull request by sartechb**
This should cover the basics for the `open` command in an easy to understand way.

### CODE REVIEW

**Comment by szechy** [comment]
I'm genuinely excited for documentation on `open`, thanks @sartechb!

**Comment by the-alex** [comment]
Excellent!
Can I get your full name and uniquename so I can merge?

**Comment by sartechb** [comment]
@the-alex yeah!

name: Sarthak Bhandari
uniqname: sarthakb

**Comment by themoh** [comment]
@sartechb This doesn't actually show up on the course webpage (a result of bad formatting). Build off of the template.md file we provide (see other merged pull requests for examples on what it should look like after edits) and issue another pull request to complete the assignment.

**Pull request merged**
